package com.pocrd.dubbo_demo.dao.autogen.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.order_no
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.user_id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.amount
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.remark
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.id
     *
     * @return the value of test_order.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.id
     *
     * @param id the value for test_order.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.order_no
     *
     * @return the value of test_order.order_no
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.order_no
     *
     * @param orderNo the value for test_order.order_no
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.user_id
     *
     * @return the value of test_order.user_id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.user_id
     *
     * @param userId the value for test_order.user_id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.amount
     *
     * @return the value of test_order.amount
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.amount
     *
     * @param amount the value for test_order.amount
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.status
     *
     * @return the value of test_order.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.status
     *
     * @param status the value for test_order.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.remark
     *
     * @return the value of test_order.remark
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.remark
     *
     * @param remark the value for test_order.remark
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.created_at
     *
     * @return the value of test_order.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.created_at
     *
     * @param createdAt the value for test_order.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.updated_at
     *
     * @return the value of test_order.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.updated_at
     *
     * @param updatedAt the value for test_order.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}