package com.pocrd.dubbo_demo.dao.autogen.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProductDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.product_code
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.product_name
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.price
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.stock
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.category
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.is_deleted
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.id
     *
     * @return the value of test_product.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.id
     *
     * @param id the value for test_product.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.product_code
     *
     * @return the value of test_product.product_code
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.product_code
     *
     * @param productCode the value for test_product.product_code
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.product_name
     *
     * @return the value of test_product.product_name
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.product_name
     *
     * @param productName the value for test_product.product_name
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.price
     *
     * @return the value of test_product.price
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.price
     *
     * @param price the value for test_product.price
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.stock
     *
     * @return the value of test_product.stock
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.stock
     *
     * @param stock the value for test_product.stock
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.category
     *
     * @return the value of test_product.category
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.category
     *
     * @param category the value for test_product.category
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.is_deleted
     *
     * @return the value of test_product.is_deleted
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.is_deleted
     *
     * @param isDeleted the value for test_product.is_deleted
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.created_at
     *
     * @return the value of test_product.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.created_at
     *
     * @param createdAt the value for test_product.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.updated_at
     *
     * @return the value of test_product.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.updated_at
     *
     * @param updatedAt the value for test_product.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}