package com.pocrd.dubbo_demo.dao.autogen.entity;

import java.util.Date;

public class UserDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.username
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.email
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.phone
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.id
     *
     * @return the value of test_user.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.id
     *
     * @param id the value for test_user.id
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.username
     *
     * @return the value of test_user.username
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.username
     *
     * @param username the value for test_user.username
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.email
     *
     * @return the value of test_user.email
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.email
     *
     * @param email the value for test_user.email
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.phone
     *
     * @return the value of test_user.phone
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.phone
     *
     * @param phone the value for test_user.phone
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.status
     *
     * @return the value of test_user.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.status
     *
     * @param status the value for test_user.status
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.created_at
     *
     * @return the value of test_user.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.created_at
     *
     * @param createdAt the value for test_user.created_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.updated_at
     *
     * @return the value of test_user.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.updated_at
     *
     * @param updatedAt the value for test_user.updated_at
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}