package com.pocrd.service_demo.dao.autogen.mapper;

import com.pocrd.service_demo.dao.autogen.entity.OrderDTO;
import com.pocrd.service_demo.dao.autogen.entity.OrderDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    long countByExample(OrderDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByExample(OrderDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insert(OrderDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insertSelective(OrderDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    List<OrderDTO> selectByExample(OrderDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    OrderDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExampleSelective(@Param("row") OrderDTO row, @Param("example") OrderDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExample(@Param("row") OrderDTO row, @Param("example") OrderDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKeySelective(OrderDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKey(OrderDTO row);
}