package com.pocrd.service_demo.dao.autogen.mapper;

import com.pocrd.service_demo.dao.autogen.entity.ProductDTO;
import com.pocrd.service_demo.dao.autogen.entity.ProductDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    long countByExample(ProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByExample(ProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insert(ProductDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insertSelective(ProductDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    List<ProductDTO> selectByExample(ProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    ProductDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExampleSelective(@Param("row") ProductDTO row, @Param("example") ProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExample(@Param("row") ProductDTO row, @Param("example") ProductDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKeySelective(ProductDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_product
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKey(ProductDTO row);
}