package com.pocrd.service_demo.dao.autogen.mapper;

import com.pocrd.service_demo.dao.autogen.entity.UserDTO;
import com.pocrd.service_demo.dao.autogen.entity.UserDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    long countByExample(UserDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByExample(UserDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insert(UserDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int insertSelective(UserDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    List<UserDTO> selectByExample(UserDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    UserDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExampleSelective(@Param("row") UserDTO row, @Param("example") UserDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByExample(@Param("row") UserDTO row, @Param("example") UserDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKeySelective(UserDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Fri Mar 06 01:23:04 CST 2026
     */
    int updateByPrimaryKey(UserDTO row);
}